### ISSUE TITLE
Create reusable coming soon component

### ISSUE THREAD

**Issue by maxellmilay** [maxellmilay/otakufest-ph#14]

**Comment by Loweso** [comment]
@maxellmilay @arwin50 this is the coming soon component:

![image](https://github.com/maxellmilay/otakufest-ph/assets/119489421/6b178cf4-dcb8-4828-9a5b-787935690c50)
![image](https://github.com/maxellmilay/otakufest-ph/assets/119489421/339b497e-6e1e-4faa-924e-b76965f5b456)

lmao i think we can do better than this...............

**Comment by maxellmilay** [comment]
I was also thinking the same thing, maybe add a mascot or something
