### ISSUE TITLE
Change transition between hero section and description section in landing page

### ISSUE THREAD

**Issue by maxellmilay** [maxellmilay/otakufest-ph#5]
Merge the background of the two sections seamlessly

![image](https://github.com/maxellmilay/otakufest-ph/assets/82187749/5a6c6d4c-2dbf-4968-b76e-2016b628574d)

**Comment by Loweso** [comment]
@maxellmilay @arwin50 here is the transition:

![image](https://github.com/maxellmilay/otakufest-ph/assets/119489421/c989d624-bebc-42cf-b15b-47c633778088)
![image](https://github.com/maxellmilay/otakufest-ph/assets/119489421/b6ab0d97-c479-45e2-95d6-e0d487703edc)

g?

**Comment by maxellmilay** [comment]
Much better
