### ISSUE TITLE
[Figma] Modal design for contact us page

### ISSUE THREAD

**Issue by arwin50** [maxellmilay/otakufest-ph#86]

**Comment by arwin50** [comment]
![Contact Us Modal Failed](https://github.com/maxellmilay/otakufest-ph/assets/112203539/d179e175-51a4-43fc-8550-734249bb4bdf)
![Contact Us Modal Success](https://github.com/maxellmilay/otakufest-ph/assets/112203539/a02adbef-ba04-4be4-bd9e-f94c7cc2fd77)

What do you think of the design? @Loweso  @maxellmilay

**Comment by Loweso** [comment]
i think this is nice na shesh
