### ISSUE TITLE
[Figma] Modal design for events section

### ISSUE THREAD

**Issue by arwin50** [maxellmilay/otakufest-ph#87]

**Comment by arwin50** [comment]
![Event Section Modal](https://github.com/maxellmilay/otakufest-ph/assets/112203539/81aaec1d-b2fb-4e65-b5f7-124a75971fad)


What do you think of the design? 

@maxellmilay @Loweso

**Comment by Loweso** [comment]
add part that shows if deadline for applications has already passed

**Comment by arwin50** [comment]
![Event Section Modal (1)](https://github.com/maxellmilay/otakufest-ph/assets/112203539/357beb77-5995-4dc2-ad6e-3d5df7e317c9)

how about this? 

@Loweso  @maxellmilay

**Comment by Loweso** [comment]
try daw nakabold cya nya naa cya sa ubos sa title @arwin50

**Comment by arwin50** [comment]
![Event Section Modal (2)](https://github.com/maxellmilay/otakufest-ph/assets/112203539/4039f4da-b8fe-49a6-9ada-8dfd0675f8da)

what do you think?

@Loweso @maxellmilay

**Comment by arwin50** [comment]
![Event Section Modal (3)](https://github.com/maxellmilay/otakufest-ph/assets/112203539/9de46f38-6fbd-4a6e-b31a-8f86a3820395)
nara finisher char @Loweso @maxellmilay

**Comment by Loweso** [comment]
sheshh oks na go koya @arwin50 godlak HAHAHAHA
